### ISSUE TITLE
Login Page With Signup

### ISSUE THREAD

**Issue by MadhushaPrasad** [sliit-foss/rsvp-frontend#16]
NOTE: users can switch between the registration form ui by clicking ‘already have an account? login’ and ‘not registered yet? sign up’ links. (animation)

**Comment by Blargian** [comment]
Hello @MadhushaPrasad, I'd like to work on this. I have some experience with React :)

**Comment by sithumonline** [comment]
> Hello @MadhushaPrasad, I'd like to work on this. I have some experience with React :)

Hiii @Blargian welcome to our community.... go-ahead, and PR. U can find the design on the readme.

**Comment by MadhushaPrasad** [comment]
yah, go-ahead, and PR. U can find the design on the readme.
Welcome to our community @Blargian

**Comment by Blargian** [comment]
@MadhushaPrasad @sithumonline Hii guys, I'm busy working on this now. I noticed I can't push to the repository because I don't have access rights. Should I just fork and push to my forked repo and then create a pull request or could you give me access? :)

**Comment by sithumonline** [comment]
> @MadhushaPrasad @sithumonline Hii guys, I'm busy working on this now. I noticed I can't push to the repository because I don't have access rights. Should I just fork and push to my forked repo and then create a pull request or could you give me access? :)

Sorry.. U have to fork the repo mate.

**Comment by MadhushaPrasad** [comment]
@Blargian you need to forke this repo

**Comment by Blargian** [comment]
Hi guys, I am taking a mobile first approach. There wasn't any design for what mobile should look like so I have to use my imagination. Could you tell me what you think - is it okay for the mobile layout? 


![signup](https://user-images.githubusercontent.com/41984034/123677008-e4a00480-d844-11eb-95cf-3749eb7d83ac.jpg)
![login](https://user-images.githubusercontent.com/41984034/123677015-e7025e80-d844-11eb-85fb-2a788771998d.jpg)

**Comment by MadhushaPrasad** [comment]
Actually we don't need to show vector icon on mobile responsive,can you please do it display:none ?

Is that right  neh @Bawanthathilan ? We don't need to show vector icon on mobile res!?

**Comment by LayanJay** [comment]
Hey @Blargian, sorry for not having the mobile layout in the design document. We just design it and moved quickly to the implementation.

By the way, it seems like you have done a great job even with your imaginative mobile layout. Firstly our team decided to hide that SVG when it shrinks to the mobile layout. But looking at ur implementation I found it looks really nice to keep that SVG in place. May be we can decrease the size a little more.

Simply, your implementation looks good for me.
