### ISSUE TITLE
Put a different BG color to what we do section

### ISSUE THREAD

**Issue by chamodshehanka** [sliit-foss/rsvp-frontend#30]
![Screenshot 2021-06-26 at 22 23 00](https://user-images.githubusercontent.com/19349315/123520194-25750d80-d6cd-11eb-9b70-c4497373a71f.png)

**Comment by LayanJay** [comment]
![456](https://user-images.githubusercontent.com/68940947/123535922-ee424300-d744-11eb-904a-fbd4f8dc29fc.PNG)
![456](https://user-images.githubusercontent.com/68940947/123536006-71fc2f80-d745-11eb-91d3-5ec598092d28.PNG)


What about this? or do I need to add a plain square color?

**Comment by sithumonline** [comment]
@LayanJay 2nd one is seen good to me

**Comment by LayanJay** [comment]
Then I'll add that one

**Comment by LayanJay** [comment]
>@sithumonline Then I'll add that one

**Comment by LayanJay** [comment]
As this issue was already solved, closing the issue
