### ISSUE TITLE
Implementation of Single event page is incorrect.

### ISSUE THREAD

**Issue by LayanJay** [sliit-foss/rsvp-frontend#74]
## Introduction
The single event page should be implemented like the way nextjs works.

## Possible reproduction
the file path should be like this
event/[eventSlug].tsx

And if we use getStaticProps we have to generate all the slugs using the getStaticPaths function.
otherwise, getServerSideProps will do the work.

**Comment by Akalanka47000** [comment]
![image](https://user-images.githubusercontent.com/73662613/126155290-253b5779-7354-4eb0-946f-55526cf792a2.png)
LIke this?

**Comment by Akalanka47000** [comment]
or should the url be dynamic like instead of singleEvent it should say the event name if that's what's meant by slugs

**Comment by LayanJay** [comment]
> or should the url be dynamic like instead of singleEvent it should say the event name if that's what's meant by slugs

It should be dynamic. And file name should be with square brackets
Ex: [slug].tsx

In here slug is a context value so use "slug" there.

**Comment by Akalanka47000** [comment]
check the PR and see if it's okay please
